### ISSUE TITLE
Pretrained models pickle missing

### ISSUE THREAD

**Issue by Omenranr** [Prasad9/Classify-HandGesturePose#7]
Hello you did a good job, but since I dont have a gpu to train you model I searched for pretrained models but they are missing can I get a download link: 
'./weights/handsegnet-rhd.pickle', 
'./weights/posenet3d-rhd-stb-slr-finetuned.pickle'

**Comment by reinholtk24** [comment]
If you look over the ReadMe it mentions that you need to download the models elsewhere. A link is provided for the 'elsewhere' of the files needed.

**Comment by Omenranr** [comment]
ok thanks
